language: python
python:
  - "3.4"
  - "2.7"
install:
  - pip install coverage
  - pip install nose
  - pip install mock
  - pip install -U setuptools
script:
  - python setup.py install
  - nosetests --with-coverage --cover-package=multicode
before_install:
  pip install codecov
after_success:
  codecov
